## Importing the libraries

In [57]:
import pandas as pd
import numpy as np

## Looking at the dataset

In [58]:
data = pd.read_csv(r'cleaned_excel.csv')
print(data.head())

   TransactionID CustomerID PurchaseDate  Product      Category  Quantity  \
0              1   CUST2620   24-04-2024    Dress  Women'S Wear         2
1              1   CUST2620   24-04-2024  Handbag   Accessories         2
2              2   CUST1409   10-09-2025    Jeans    Bottomwear         1
3              2   CUST1409   10-09-2025     Belt   Accessories         3
4              2   CUST1409   10-09-2025   Shorts    Bottomwear         3

   UnitPrice       City  Gender  Age
0     1442.0     Mumbai  Female   65
1     3978.0  Bangalore    Male   55
2     4821.0  Bangalore    Male   36
3     4013.0  Bangalore  Female   58
4     4861.0     Mumbai    Male   32

## Knowing about the data more

In [59]:
data.dtypes

TransactionID      int64
CustomerID           str
PurchaseDate         str
Product              str
Category             str
Quantity           int64
UnitPrice        float64
City                 str
Gender               str
Age                int64
dtype: object

In [60]:
data.isna().sum()

TransactionID    0
CustomerID       0
PurchaseDate     0
Product          0
Category         0
Quantity         0
UnitPrice        0
City             0
Gender           0
Age              0
dtype: int64

In [61]:
data.describe()

       TransactionID      Quantity     UnitPrice           Age
count   15000.000000  15000.000000  15000.000000  15000.000000
mean     2504.053467      3.537733   2913.240400     41.382867
std      1445.444344      6.313438   4820.502693     13.787536
min         1.000000      1.000000      0.000000     12.000000
25%      1249.750000      2.000000   1466.750000     30.000000
50%      2499.000000      3.000000   2596.000000     41.000000
75%      3767.000000      4.000000   3795.000000     53.000000
max      5000.000000    100.000000  99999.000000     92.000000

## Cleaning the data

### Date Cleaning

In [62]:
def parse_mixed_date(x):
    try:
        return pd.to_datetime(x, format='%d-%m-%Y')
    except:
        try:
            return pd.to_datetime(x, format='%m-%d-%Y')
        except:
            return pd.NaT

data['PurchaseDate'] = data['PurchaseDate'].astype(str).apply(parse_mixed_date)

data['PurchaseDate'] = data['PurchaseDate'].dt.strftime('%d-%m-%Y')

In [63]:
data['Purchasedate'] = pd.to_datetime(data['PurchaseDate'], format='%d-%m-%Y')

### City Cleaning

In [64]:
data['City'] = data['City'].fillna(data['City'].mode()[0])

### UnitPrice Cleaning

In [65]:
data['UnitPrice'] = data['UnitPrice'].fillna(data['UnitPrice'].median())

### Age Cleaning

In [66]:
data['Age'] = data['Age'].fillna(data['Age'].median())
data['Age'] = data['Age'].astype(np.int32)

### Gender Cleaning

In [67]:
data['Gender'] = data['Gender'].replace({'F':'Female', 'M':'Male'})

In [68]:
for i in range(len(data)):
    if data.loc[i, 'Category'] == "Women's Wear" or \
       'dress' in data.loc[i, 'Product'].lower() or \
       'skirt' in data.loc[i, 'Product'].lower():
        data.loc[i, 'Gender'] = "Female"

In [69]:
data['Gender'] = data['Gender'].fillna(data['Gender'].mode()[0])

In [70]:
data = data.drop(data.columns[-1], axis=1)

## Saved the data

In [71]:
data.to_csv(r'cleaned_excel.csv', index=False)

In [72]:
data.head()

,TransactionID,CustomerID,PurchaseDate,Product,Category,Quantity,UnitPrice,City,Gender,Age
0,1,CUST2620,24-04-2024,Dress,Women'S Wear,2,1442.0,Mumbai,Female,65
1,1,CUST2620,24-04-2024,Handbag,Accessories,2,3978.0,Bangalore,Male,55
2,2,CUST1409,10-09-2025,Jeans,Bottomwear,1,4821.0,Bangalore,Male,36
3,2,CUST1409,10-09-2025,Belt,Accessories,3,4013.0,Bangalore,Female,58
4,2,CUST1409,10-09-2025,Shorts,Bottomwear,3,4861.0,Mumbai,Male,32